### ISSUE TITLE
Problem with loading bruteforce pressing 5

### ISSUE THREAD

**Issue by fkay9** [MBHudson/Vigilante-Toolset#1]
I am new to this toolset when I press 5 for bruteforce I get "./Vigilante: line 50: press_enter: command not found" and no window for bruteforcing pops up after. Is this suppose to happen? If so what do I do to actually start the attack

**Comment by fkay9** [comment]
I think all the options I been getting this with

**Comment by MBHudson** [comment]
Sorry, I just now noticed that almost half my code is missing. Not sure why, I will have this fixed by the end of the day when I get to my computer. I apologize for the delay.

**Comment by fkay9** [comment]
Alright tell me when its fixed

**Comment by MBHudson** [comment]
Script was missing files. Files uploaded, should be fixed.
